project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-JBWPRMFXM3"
  title: "Fabian Prettenthaler"
  favicon: "FP_logo.png"
  navbar:
    right:
      - blog.qmd
 #     - icon: twitter
  #      href: https://twitter.com/FabianPrettent1
   #   - text: CV
    #    href: CV/CV_FP.pdf
  page-footer:
    background: dark # or dark
    left:
      - "Copyright 2024, Fabian Prettenthaler"
        
format:
  html:
    theme: darkly
    css: styles.css#
    
grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px


editor: visual

